apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authapi
  name: authapi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: authapi
  template:
    metadata:
      labels:
        app: authapi
    spec:
      containers:
      - env:
        - name: MAMONGO_HOST
          valueFrom:
            configMapKeyRef:
              key: MAMONGO_HOST
              name: db-env
        - name: MASQL_HOST
          valueFrom:
            configMapKeyRef:
              key: MASQL_HOST
              name: db-env
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: db-env
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: db-env
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: db-env   
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: node-env
        - name: jwtSecret
          valueFrom:
            configMapKeyRef:
              key: jwtSecret
              name: node-env
        - name: email
          valueFrom:
            configMapKeyRef:
              key: email
              name: email-env
        - name: email_password
          valueFrom:
            configMapKeyRef:
              key: email_password
              name: email-env
        - name: confidentLevel
          value: '0.100'
        - name: cycle
          value: '100'
        - name: mode
          value: AFM
        image: msbunecsc/cb-authapi
        name: authapi
        volumeMounts:
        - mountPath: /home/node/app/env
          name: env-var
          readOnly: true
        - mountPath: /home/node/app/volume/authapi
          subPath: authapi
          name: authapi-pv
      restartPolicy: Always
      volumes:
      - name: authapi-pv
        persistentVolumeClaim:
          claimName: authapi-claim
      - name: env-var
        configMap:
          name: env-var
          items:
            - key: .env
              path: .env

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: authapi
  name: authapi
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: authapi
status:
  loadBalancer: {}
