apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fileserver
  name: fileserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fileserver
  template:
    metadata:
      labels:
        app: fileserver
    spec:
      containers:
      - image: msbunecsc/cb-fileserver
        name: fileserver
        volumeMounts:
        - mountPath: /home/node/app/static
          name: filestoragevol
      restartPolicy: Always
      volumes:
      - name: filestoragevol
        persistentVolumeClaim:
          claimName: filestorage-claim
---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: fileserver
  name: fileserver
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: fileserver
status:
  loadBalancer: {}
