apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: livechatapi
  name: livechatapi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: livechatapi
  template:
    metadata:
      labels:
        app: livechatapi
    spec:
      containers:
      - env:
        - name: MAMONGO_HOST
          valueFrom:
            configMapKeyRef:
              key: MAMONGO_HOST
              name: db-env
        - name: MASQL_HOST
          valueFrom:
            configMapKeyRef:
              key: MASQL_HOST
              name: db-env
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: db-env
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: db-env
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: db-env   
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: node-env
        - name: jwtSecret
          valueFrom:
            configMapKeyRef:
              key: jwtSecret
              name: node-env
        image: msbunecsc/cb-livechatapi
        name: livechatapi
        volumeMounts:
        - mountPath: /home/node/app/volume
          name: livechatapi-pv
      restartPolicy: Always
      volumes:
      - name: livechatapi-pv
        persistentVolumeClaim:
          claimName: livechatapi-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: livechatapi
  name: livechatapi
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: livechatapi
status:
  loadBalancer: {}
