apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trainengine
  name: trainengine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trainengine
  template:
    metadata:
      labels:
        app: trainengine
    spec:
      containers:
      - image: msbunecsc/cb-trainengine
        name: trainengine
        ports:
        - containerPort: 8099
        volumeMounts:
        - mountPath: /home/node/app/dialogues
          subPath: dialogues
          name: dialogues-pv
        - mountPath: /home/node/app/coreengine
          subPath: coreengine
          name: coreengine-pv
      restartPolicy: Always
      volumes:
      - name: coreengine-pv
        persistentVolumeClaim:
          claimName: coreengine-claim
      - name: coreengine-pv
        persistentVolumeClaim:
          claimName: coreengine-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: trainengine
  name: trainengine
spec:
  ports:
  - name: "8099"
    port: 8099
    targetPort: 8099
  selector:
    app: trainengine
status:
  loadBalancer: {}

